[package]
name = "monitor-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
monitor-common = { path = "../monitor-common" }
tokio = { workspace = true }
